////------------------------------------------------------------------------------
//// <auto-generated>
////     This code was generated by a tool.
////
////     Changes to this file may cause incorrect behavior and will be lost if
////     the code is regenerated.
//// </auto-generated>
////------------------------------------------------------------------------------

//// Generated from: rpc.proto
//namespace rpc
//{
//  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RpcRequest")]
//  public partial class RpcRequest : global::ProtoBuf.IExtensible
//  {
//    public RpcRequest() {}
    
//    private uint _id = default(uint);
//    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
//    [global::System.ComponentModel.DefaultValue(default(uint))]
//    public uint id
//    {
//      get { return _id; }
//      set { _id = value; }
//    }
//    private string _service = "";
//    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"service", DataFormat = global::ProtoBuf.DataFormat.Default)]
//    [global::System.ComponentModel.DefaultValue("")]
//    public string service
//    {
//      get { return _service; }
//      set { _service = value; }
//    }
//    private string _method = "";
//    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"method", DataFormat = global::ProtoBuf.DataFormat.Default)]
//    [global::System.ComponentModel.DefaultValue("")]
//    public string method
//    {
//      get { return _method; }
//      set { _method = value; }
//    }
//    private byte[] _content = null;
//    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"content", DataFormat = global::ProtoBuf.DataFormat.Default)]
//    [global::System.ComponentModel.DefaultValue(null)]
//    public byte[] content
//    {
//      get { return _content; }
//      set { _content = value; }
//    }
//    private global::ProtoBuf.IExtension extensionObject;
//    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
//      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
//  }
  
//  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RpcResponse")]
//  public partial class RpcResponse : global::ProtoBuf.IExtensible
//  {
//    public RpcResponse() {}
    
//    private uint _id;
//    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
//    public uint id
//    {
//      get { return _id; }
//      set { _id = value; }
//    }
//    private byte[] _content = null;
//    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"content", DataFormat = global::ProtoBuf.DataFormat.Default)]
//    [global::System.ComponentModel.DefaultValue(null)]
//    public byte[] content
//    {
//      get { return _content; }
//      set { _content = value; }
//    }
//    private global::ProtoBuf.IExtension extensionObject;
//    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
//      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
//  }
  
//  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RpcPackage")]
//  public partial class RpcPackage : global::ProtoBuf.IExtensible
//  {
//    public RpcPackage() {}
    
//    private rpc.RpcRequest _request = null;
//    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"request", DataFormat = global::ProtoBuf.DataFormat.Default)]
//    [global::System.ComponentModel.DefaultValue(null)]
//    public rpc.RpcRequest request
//    {
//      get { return _request; }
//      set { _request = value; }
//    }
//    private rpc.RpcResponse _response = null;
//    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"response", DataFormat = global::ProtoBuf.DataFormat.Default)]
//    [global::System.ComponentModel.DefaultValue(null)]
//    public rpc.RpcResponse response
//    {
//      get { return _response; }
//      set { _response = value; }
//    }
//    private global::ProtoBuf.IExtension extensionObject;
//    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
//      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
//  }
  
//}